version: "3"
services:
  php-apache:
    image: php:7.0-apache
    ports:
      - "80:80"
    volumes:
      - ./public/:/var/www/html/
    networks:
      - frontend

networks:
  frontend:

volumes:
  db-data: