version: "3"
services:
  php-apache:
    image: php:7.0-apache
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/
    networks:
      - frontend
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public

networks:
  frontend:

volumes:
  db-data: